# Generated by Django 2.1.4 on 2019-01-14 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='published_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
